/**
 * Shielded-pool PTB harness (Workstream C end-to-end).
 *
 * Exercises the REAL SDK in Node to produce the on-chain DEPOSIT and WITHDRAW
 * `transact` PTBs for a fixed test note, using REAL Groth16 proofs generated by
 * the Rust prover (move/talise-privacy/circuit) and the REAL ECIES note
 * encryption (encrypt.ts). It then serializes both PTBs to base64 transaction
 * bytes (onlyTransactionKind — sender/gas left for the relayer to set, exactly
 * as flow.ts does before POSTing to /api/shield/relay).
 *
 * The Groth16 proof artifacts below are copied verbatim from:
 *   cargo run --release --bin prove_deposit -- \
 *     --pool 0x6bcd...152c1 --root 0 --amount 1000
 *   cargo run --release --bin prove_withdraw_harness
 * Both NATIVE-verified against the persisted VK (== on-chain VK). The harness
 * re-maps proof_hex + the 8 public inputs into the SDK's ProofInputs shape and
 * drives buildTransact — no chain access, no funds.
 *
 * Run:  npx vitest run --config vitest.integration.config.ts \
 *         __tests__/sui/shield-ptb-harness.test.ts
 */
import { describe, it, expect } from "vitest";
import { Transaction, Inputs } from "@mysten/sui/transactions";
import { bcs } from "@mysten/sui/bcs";
import { buildTransact, type ProofInputs, type ExtDataInput } from "@/lib/shield/sdk/tx";
import { encryptNote, encPublicKeyFromScalar } from "@/lib/shield/sdk/encrypt";
import { deriveShieldKeypairFromSeed, deriveShieldEncScalar } from "@/lib/shield/sdk/keys";
import { USDSUI_TYPE } from "@/lib/usdsui";

// ── Live (mainnet) pool wiring ────────────────────────────────────────────────
const PACKAGE_ID =
  "0x8722790773958722225cf91f5a6762689dc13f97076534c05ebd3505d586f9bf";
const POOL_OBJECT_ID =
  "0x6bcd28763456db543d0c29acb34970b81e4d7f004d2581fce46b813ece8152c1";
// The funded relayer (ExtData.relayer + tx sender + zero-coin source owner).
const RELAYER =
  "0x37949e572bbc9cd57b7817cf3d309c0fa1b5361e0bc7605f6feffc6b6fdb72af";
// Placeholder object ids for the coin legs (real ids supplied at relay time).
const DEPOSIT_COIN_ID =
  "0x1111111111111111111111111111111111111111111111111111111111111111";
const ZERO_COIN_SOURCE_ID =
  "0x2222222222222222222222222222222222222222222222222222222222222222";
const EXIT_ADDRESS =
  "0x3333333333333333333333333333333333333333333333333333333333333333";

// ── REAL Groth16 proof artifacts (from the Rust prover, native-verified) ──────
// proof_hex = A32|B64|C32 compressed = 128 bytes; public inputs in allocation
// order [pool, root, public_value, null0, null1, comm0, comm1, hashed_secret].

const DEPOSIT = {
  proofHex:
    "5020fd816849f98d4f4289829ccadd536a48399f09a877973a1882c6e146231c" +
    "699a2854f44d3d9d25f4b5de16bc62ff303e379f9211f9f167adad5b40dd701c" +
    "6611886acb629f5d7d8d3d73b58331d59f3f06cc02e9c34d2ffd60bdc6549b80" +
    "cb84a94a558ecd087c40810ef2b499b39b3d4b88a35774972e46406edba50f80",
  root: 0n,
  publicValue: 1000n,
  null0: 8874489674610852055365825450502871696107617634674944839590774381311671432138n,
  null1: 14735100347003117441335642801124275357118802347964005792522872815119077059237n,
  comm0: 10899760595461394734908702959981595356369358741961556886393143045034375590965n,
  comm1: 12013773756360371331370722014999054062474954786002594294326912317717327531506n,
};

const WITHDRAW = {
  proofHex:
    "9a2448e38ddc8f0b6f97aee7bf68e3aaf500df2f370d6767d2a8fc2a7f93168c" +
    "208dec5c51326279ef44457fadebcb6fb1504fe23a026c953fa5f41a5f602315" +
    "9fd81a808c22ebfbbd5ad099afba8b61fa7925f04cde5e58b37cfa0e1879bb0e" +
    "964ce254230a64cc30080da0b8c9775c3c89e9a31c3ed34f8d33e5a54cb14b30",
  // root = reconstructed height-26 root after the deposit's two leaves.
  root: 21299735462063983358185664815009242608878032591883643376265563669177668845388n,
  // public_value = field-negated 1000 (r - 1000).
  publicValue: 21888242871839275222246405745257275088548364400416034343698204186575808494617n,
  null0: 17365993652607252536207177426781989436768987297164408994060731883744541373214n,
  null1: 19675119579309133727559111446548914456322699056414605618053998085928210688930n,
  comm0: 1004813861286602095921333519409224192067649416039090645479339872202520620727n,
  comm1: 6793229471391900658229276096589399136326421784747819562673931439168574900104n,
};

function hexToBytes(hex: string): Uint8Array {
  const m = hex.match(/.{1,2}/g);
  if (!m) throw new Error("empty hex");
  return Uint8Array.from(m.map((b) => parseInt(b, 16)));
}

function toB64(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString("base64");
}

async function buildExt(
  valueSign: boolean,
  value: bigint
): Promise<ExtDataInput> {
  // Fixed test note keypair (seed -> spending key -> enc scalar -> P-256 pubkey).
  const seed = new Uint8Array(32).fill(7);
  const kp = await deriveShieldKeypairFromSeed(seed);
  const d = await deriveShieldEncScalar(kp.spendingKey);
  const selfPub = encPublicKeyFromScalar(d);
  // REAL ECIES blobs for the two output notes (amounts here are illustrative —
  // the proof binds the real commitments; the blob is just the recovery payload).
  const enc0 = await encryptNote(
    { amount: value, pubkey: kp.publicKey, blinding: 777n, pool: BigInt(POOL_OBJECT_ID) },
    selfPub
  );
  const enc1 = await encryptNote(
    { amount: 0n, pubkey: kp.publicKey, blinding: 666n, pool: BigInt(POOL_OBJECT_ID) },
    selfPub
  );
  return {
    value,
    valueSign,
    relayer: RELAYER,
    relayerFee: 0n,
    encryptedOutput0: enc0,
    encryptedOutput1: enc1,
  };
}

// Real shared version of the on-chain pool (probed from mainnet fullnode:
// owner = Shared { initial_shared_version: 919114728 }). Lets the harness build
// the transaction-kind BCS bytes fully OFFLINE (no client) by giving every
// object an explicit reference. Fabricated owned-coin refs stand in for the
// relayer's real coin (resolved at relay time); the resulting BCS bytes are a
// well-formed TransactionKind — the exact shape the relayer signs + submits.
const POOL_SHARED_VERSION = 919114728;
const FAKE_DIGEST = "11111111111111111111111111111111"; // base58, 32 zero-ish bytes

function fakeOwnedRef(objectId: string, version = 1) {
  return Inputs.ObjectRef({ objectId, version, digest: FAKE_DIGEST });
}

/**
 * Re-assemble the EXACT transact PTB shape buildTransact produces, but with
 * explicit object references so it serializes offline. Mirrors tx.ts line-for-
 * line (proof::new -> ext_data::new -> [split zero coin] -> shielded_pool::
 * transact -> transferObjects). Offline-only artifact generator.
 */
function buildTransactOffline(p: {
  proof: ProofInputs;
  ext: ExtDataInput;
  depositCoinId?: string;
  zeroCoinSourceId?: string;
  outputRecipient: string;
}): Transaction {
  const tx = new Transaction();
  const proofArg = tx.moveCall({
    target: `${PACKAGE_ID}::proof::new`,
    typeArguments: [USDSUI_TYPE],
    arguments: [
      tx.pure.address(POOL_OBJECT_ID),
      tx.pure(bcs.vector(bcs.u8()).serialize(p.proof.proofPoints)),
      tx.pure(bcs.u256().serialize(p.proof.root)),
      tx.pure(bcs.u256().serialize(p.proof.publicValue)),
      tx.pure(bcs.u256().serialize(p.proof.inputNullifier0)),
      tx.pure(bcs.u256().serialize(p.proof.inputNullifier1)),
      tx.pure(bcs.u256().serialize(p.proof.outputCommitment0)),
      tx.pure(bcs.u256().serialize(p.proof.outputCommitment1)),
    ],
  });
  const extArg = tx.moveCall({
    target: `${PACKAGE_ID}::ext_data::new`,
    arguments: [
      tx.pure(bcs.u64().serialize(p.ext.value)),
      tx.pure(bcs.bool().serialize(p.ext.valueSign)),
      tx.pure.address(p.ext.relayer),
      tx.pure(bcs.u64().serialize(p.ext.relayerFee)),
      tx.pure(bcs.vector(bcs.u8()).serialize(p.ext.encryptedOutput0)),
      tx.pure(bcs.vector(bcs.u8()).serialize(p.ext.encryptedOutput1)),
    ],
  });
  let depositCoin;
  if (p.depositCoinId) {
    depositCoin = tx.object(fakeOwnedRef(p.depositCoinId));
  } else if (p.zeroCoinSourceId) {
    const [zero] = tx.splitCoins(tx.object(fakeOwnedRef(p.zeroCoinSourceId)), [
      tx.pure.u64(0n),
    ]);
    depositCoin = zero;
  } else {
    throw new Error("need depositCoinId or zeroCoinSourceId");
  }
  const out = tx.moveCall({
    target: `${PACKAGE_ID}::shielded_pool::transact`,
    typeArguments: [USDSUI_TYPE],
    arguments: [
      tx.object(
        Inputs.SharedObjectRef({
          objectId: POOL_OBJECT_ID,
          initialSharedVersion: POOL_SHARED_VERSION,
          mutable: true,
        })
      ),
      depositCoin,
      proofArg,
      extArg,
    ],
  });
  tx.transferObjects([out], tx.pure.address(p.outputRecipient));
  return tx;
}

describe("shield PTB harness (real proofs)", () => {
  it("builds the DEPOSIT transact PTB", async () => {
    const proof: ProofInputs = {
      proofPoints: hexToBytes(DEPOSIT.proofHex),
      root: DEPOSIT.root,
      publicValue: DEPOSIT.publicValue,
      inputNullifier0: DEPOSIT.null0,
      inputNullifier1: DEPOSIT.null1,
      outputCommitment0: DEPOSIT.comm0,
      outputCommitment1: DEPOSIT.comm1,
    };
    expect(proof.proofPoints.length).toBe(128);

    const ext = await buildExt(true, 1000n);
    const tx = buildTransact({
      packageId: PACKAGE_ID,
      coinType: USDSUI_TYPE,
      poolObjectId: POOL_OBJECT_ID,
      poolAddress: POOL_OBJECT_ID,
      proof,
      ext,
      depositCoinId: DEPOSIT_COIN_ID,
      outputRecipient: RELAYER, // deposit return coin is zero -> relayer
    });

    // The real relay artifact: the unbuilt transaction serialized by the SDK
    // (exactly what flow.ts POSTs to /api/shield/relay; the relayer resolves
    // objects + sets sender/gas).
    const relayJson = await tx.toJSON();
    // Offline base64 transaction-kind BCS bytes (explicit object refs).
    const offline = buildTransactOffline({
      proof,
      ext,
      depositCoinId: DEPOSIT_COIN_ID,
      outputRecipient: RELAYER,
    });
    const bytes = await offline.build({ onlyTransactionKind: true });
    const b64 = toB64(bytes);
    // eslint-disable-next-line no-console
    console.log("\n=== DEPOSIT PTB (base64 TransactionKind, offline) ===\n" + b64 + "\n");
    // eslint-disable-next-line no-console
    console.log("=== DEPOSIT PTB JSON (real SDK relay payload) ===\n" + relayJson + "\n");
    expect(b64.length).toBeGreaterThan(0);
    expect(relayJson).toContain("shielded_pool");
  });

  it("builds the WITHDRAW transact PTB (with trailing TransferObjects to exit)", async () => {
    const proof: ProofInputs = {
      proofPoints: hexToBytes(WITHDRAW.proofHex),
      root: WITHDRAW.root,
      publicValue: WITHDRAW.publicValue,
      inputNullifier0: WITHDRAW.null0,
      inputNullifier1: WITHDRAW.null1,
      outputCommitment0: WITHDRAW.comm0,
      outputCommitment1: WITHDRAW.comm1,
    };
    expect(proof.proofPoints.length).toBe(128);

    const ext = await buildExt(false, 1000n);
    const tx = buildTransact({
      packageId: PACKAGE_ID,
      coinType: USDSUI_TYPE,
      poolObjectId: POOL_OBJECT_ID,
      poolAddress: POOL_OBJECT_ID,
      proof,
      ext,
      zeroCoinSourceId: ZERO_COIN_SOURCE_ID, // split [0] off a relayer coin
      outputRecipient: EXIT_ADDRESS, // withdrawn funds -> exit address
    });

    const relayJson = await tx.toJSON();
    const offline = buildTransactOffline({
      proof,
      ext,
      zeroCoinSourceId: ZERO_COIN_SOURCE_ID,
      outputRecipient: EXIT_ADDRESS,
    });
    const bytes = await offline.build({ onlyTransactionKind: true });
    const b64 = toB64(bytes);
    // eslint-disable-next-line no-console
    console.log("\n=== WITHDRAW PTB (base64 TransactionKind, offline) ===\n" + b64 + "\n");
    // eslint-disable-next-line no-console
    console.log("=== WITHDRAW PTB JSON (real SDK relay payload) ===\n" + relayJson + "\n");
    expect(b64.length).toBeGreaterThan(0);
    expect(relayJson).toContain("shielded_pool");
  });
});
